# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'
        cache: 'maven'
    - id: install-secret-key
      name: Install gpg secret key
      run: |
        cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
        gpg --list-secret-keys --keyid-format LONG
    - name: Effective pom
      run: mvn -B help:effective-pom
    - name: Effective settings
      run: mvn -B help:effective-settings
    - name: Build with Maven
      run: mvn -B package
      env:
        NOBAD: true
        MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSPHRASE }}
    - name: Maven deploy to Github
      run: mvn -B -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/nelbrecht/helikopterparent -Dmaven.test.skip=true -Dmaven.main.skip deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSPHRASE }}
